### ISSUE TITLE
Filter automerging by author

### ISSUE THREAD

**Issue by Aaronontheweb** [chdsbd/kodiak#178]
Possibly related to https://github.com/chdsbd/kodiak/issues/87

I'd like to have the ability to make it more secure to operate Kodiak on OSS projects - specifically, I'd like to have the ability to filter auto-merging by _who sent the request_. 

Some use cases:

* If it's someone within my OSS organization, I'd be more lenient on automatically merging the PR than I would be if it's someone outside the organization.
* If the PR is sent by dependabot or some other trusted bot installed into our org, I'd be comfortable automatically merging those.
* In the event of a single maintainer project, the maintainer might want their own PRs merged automatically but no one else's.

**Comment by chdsbd** [comment]
Are you considering using Kodiak with `merge.require_automerge_label = false`? I think if you used automerge labels you could solve all of your use cases because only organization members can add labels and you can [configure dependabot to add labels](https://dependabot.com/docs/config-file/#default_labels) to its PRs.

If you need to use Kodiak without labels I think a few config options could be added (names TBD):

```toml
# only automerge a PR without a label if it is from a member of the GitHub organization
merge.restrict_automerge_to_org_members = true
# automerge PRs created by users in this list
merge.username_automerge_whitelist = ['dependabot']
```

I'm curious to hear your thoughts.
