### ISSUE TITLE
Clarifications about the workflow

### ISSUE THREAD

**Issue by rgreinho** [chdsbd/kodiak#213]
We're having the problem that kodiak does not update the branches of our PRs when the base branch receives some changes:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/6969134/71651423-e38b2700-2ce2-11ea-8a2b-54064c650a9a.png">

It looks like kodiak is first waiting for the approvals, then will update the branch? However, none of the team members will ever give an approval to a branch which is not up to date. Therefore we end up manually updating our PRs.

We hoped that kodiak would first ensure the branch is up to date before performing any other check.

Is there a way to specify the order of the kodiak operations?

**Comment by chdsbd** [comment]
I think `merge.update_branch_immediately = true` will give you what you need. With this setting Kodiak will update a branch whenever it is out of date.

There’s some more documentation here: https://github.com/chdsbd/kodiak/blob/master/README.md#config-with-comments-and-all-options-set

When https://github.com/chdsbd/kodiak/pull/198 is finished there should be more configuration available for controlling updates, like ignoring “required approving reviews” when updating a pull request. 

Let me know if you have any questions.

**Comment by rgreinho** [comment]
We do have the `update_branch_immediately = true` in place, but it does not do what we expect. Possibly a bug?

Bellow is our configuration file:

```toml
# configuration with all defaults set
version = 1 # required

[merge]
require_automerge_label = false
blacklist_title_regex = "^WIP:.*"
blacklist_labels = ["do-not-merge"]
method = "squash"
delete_branch_on_merge = true
update_branch_immediately = true
prioritize_ready_to_merge = true
```

**Comment by chdsbd** [comment]
Sorry about that, I was mistaken.  `merge.update_branch_immediately` only affects PRs that are considered "mergeable". I think https://github.com/chdsbd/kodiak/pull/198 will allow Kodiak to fit your workflow.

#198 should be fixed soon after #207 is merged.

**Comment by rgreinho** [comment]
Awesome! Thank you so much!

**Comment by chdsbd** [comment]
#198 has been released so you should now be able to use `update.always` and `update.require_automerge_label`.

example configuration

```toml
version = 1

[update]
# update PR whenever the PR is out of date with the base branch. PR will be
# updated regardless of failing status checks, missing reviews, merge blacklist
# labels, etc. Kodiak will only update the PR if the automerge label is attached
# or `update.require_automerge_label` is false.
always = true
require_automerge_label = true
```

Let me know if you have any questions.
