### ISSUE TITLE
handle "This branch cannot be rebased due to conflicts"

### ISSUE THREAD

**Issue by chdsbd** [chdsbd/kodiak#222]
Right now Kodiak doesn't detect if a branch "cannot be rebased due to conflicts" and will attempt to call the GitHub api to merge the branch. The GitHub api returns a 405 when we try to merge using rebase because it's not possible. We should be able to detect this before attempting to merge a PR, like we do with merge conflicts.

```
url = "https://api.github.com/repos/acmecorp/api/pulls/3456/merge"
body = {"merge_method": "rebase"}
method = "PUT"
response = {"message":"This branch can\'t be rebased","documentation_url":"https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button"}
```

For the user we display a relatively unhelpful status check: 
```
⚠️ problem contacting GitHub API with method 'merge'
```

---

I think we can use the `canBeRebased` on a pull request to determine if a PR cannot merge rebased! 🎉 

EDIT: I don't think this is super high priority since Kodiak only provides a poor status message in this unlikely case. I think a quick fix would be to use the "message" key of the GitHub api response, since `canBeRebased` doesn't appear to work.

**Comment by chdsbd** [comment]
As described in #236, it appears that #225 did not fix this issue. It seems that `canBeRebased` is returning false when a PR is first opened. As a workaround we may be able to do a retry if canBeRebased is false, but I'm worried about glitchy behavior.

Also, the GitHub v3 api has a property called `rebaseable`, that is null, false, and true, which may allow us to work around `canBeRebased` shortcomings.

**Comment by Bexanderthebex** [comment]
Hello, we are experiencing this regardless of merge method - rebase/merge/squash.

For more context, here is our config, the auto update branch feature just wont work.

```toml
# .kodiak.toml
version = 1

[merge]
automerge_label = ":jack_o_lantern: squashy mergy :ship:"
require_automerge_label = true
delete_branch_on_merge = true
notify_on_conflict = true
optimistic_updates = false
prioritize_ready_to_merge = false
method = "rebase"
do_not_merge = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pull_request_url = false
include_pr_number = true
body_type = "markdown"
strip_html_comments = false

[update]
always = true
require_automerge_label = false

blacklist_usernames = ["dependabot"]

```
