### ISSUE TITLE
problem contacting GitHub API with method 'merge'

### ISSUE THREAD

**Issue by tobilen** [chdsbd/kodiak#295]
we started seeing this error yesterday. no more information than that:
![image](https://user-images.githubusercontent.com/8217788/74815853-491a8d80-52fa-11ea-8aa9-44cf17a97745.png)

our kodiak config:
```toml
version = 1

[merge]
method = "rebase"
automerge_label = "automerge"
blacklist_title_regex = "^\\[?WIP.*"
blacklist_labels = ["do not merge"]
optimistic_updates = false
delete_branch_on_merge = true

```

**Comment by chdsbd** [comment]
Thanks for reporting this. Does this happen on all pull requests? Also, do you know if the PR had a rebase conflict, because that isn’t handled at the moment.

I’m going to look through the logs and see what happened.

**Comment by chdsbd** [comment]
Looking at the logs it seems this is the same issue as https://github.com/chdsbd/kodiak/issues/222.

```
{"message":"This branch can't be rebased","documentation_url":"https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button"}
```

#222 is a bit challenging to fix do to some weirdness in the GitHub API, so I think it might be easier to improve the GitHub status message to include the API response from GitHub.

Does this issue happen frequently for you?

Thanks again for raising this issue.

**Comment by tobilen** [comment]
not very frequently, no. we have around a dozen PRs in a given 24hr cycle, and it has happened on 3 in the last two days.

**Comment by JohannesRudolph** [comment]
I had a similar issue today. We had branch protection configured to `Require linear history` and had kodiak [mergemethod](https://kodiakhq.com/docs/config-reference#mergemethod) still on `merge`. This resulted in the same GitHub API error mentioned here. I was able to figure out I forgot to configure `rebase` as the mergemethod, then it worked just fine. 

It would be great if kodiak could return a more helpful error message in this case. 

Also useful would be a way to "force" kodiak to refresh a PR status, i.e. by posting a specific comment. I was able to overcome this by simply ammending a commit and force-pushing the PR again, but that felt a bit hacky.

**Comment by chdsbd** [comment]
I'll take a look at improving the error message soon.

Regarding forcing Kodiak to refresh the PR status, you should be able to do that by modifying the PR (editing the title or body, adding/removing a label, creating a comment, pushing a commit).

**Comment by tobilen** [comment]
just saw your edit, its the `ivx` org. issue hasn't occurred anymore as far as i know. we did switch away from rebase back to merge, so maybe thats related?

**Comment by chdsbd** [comment]
@tobilen yeah, I think this issue occurs with rebase.

**Comment by Bexanderthebex** [comment]
Hello, we are experiencing this regardless of merge method - rebase/merge/squash.

For more context, here is our config, the auto update branch feature just wont work.

```toml
# .kodiak.toml
version = 1

[merge]
automerge_label = ":jack_o_lantern: squashy mergy :ship:"
require_automerge_label = true
delete_branch_on_merge = true
notify_on_conflict = true
optimistic_updates = false
prioritize_ready_to_merge = false
method = "rebase"
do_not_merge = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pull_request_url = false
include_pr_number = true
body_type = "markdown"
strip_html_comments = false

[update]
always = true
require_automerge_label = false

blacklist_usernames = ["dependabot"]

```
