### ISSUE TITLE
Update by Comment Strategy

### ISSUE THREAD

**Issue by austince** [chdsbd/kodiak#438]
Coming from #150 and the ability to add new update strategies, what do you all think about an update strategy that just makes a comment on the PR and allows other processes to handle the actual update? Not sure if this would work/ work well, but it might help Kodiak stay flexible without having to implement all the different update strategies out there. Would make working with other bots easier as well.

How it might work:

```yaml
update_strategy:
  - method: comment
    body: "@dependabot rebase"
```

Just throwing this out there, let me know what you think!

**Comment by chdsbd** [comment]
Is your dependabot example just an example for discussion or an actual issue you've encountered? I think the example in the Kodiak docs should work with rebase merging. https://kodiakhq.com/docs/recipes#automated-dependency-updates-with-dependabot

```toml
# .kodiak.toml
version = 1

[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot-preview[bot]" use "dependabot-preview".
auto_approve_usernames = ["dependabot-preview"]

# if using `update.always`, add dependabot-preview to the blacklist to allow
# dependabot to update and close stale dependency upgrades.
[update]
blacklist_usernames = ["dependabot-preview"]
```


I think comment or label based update strategies could be implemented.

It's a little more work than the default case because the GItHub merge API is idempotent, so Kodiak is safe to try multiple times whereas commenting is not, so we'd need to query to check for comments matching that content before adding one.

Somewhat related is https://github.com/chdsbd/kodiak/pull/335.
