### ISSUE TITLE
[docs] “Efficiency and Speed” recipe confusing

### ISSUE THREAD

**Issue by jglick** [chdsbd/kodiak#475]
https://kodiakhq.com/docs/config-reference#mergeoptimistic_updates says that the default is true and it can speed up merges. Makes sense so far.

https://kodiakhq.com/docs/recipes#efficiency-and-speed says it

> prioritizes resource conservation by only updating a PR when it is ready to merge

which sounds to me like it should be turning off optimistic updates. Yet the sample says

```toml
[merge]
# don't wait for running status checks when a PR needs update.
optimistic_updates = true # default: true
```

overriding a default of `true` with an explicit `true`? Which would seem to be prioritizing speed over resource conservation? Perhaps I am fundamentally misunderstanding the idea and this can be closed, but thought I would file it just in case there is a mistake or a simple way to clarify the purpose of the recipe.
