### ISSUE TITLE
[question] How to rebase !fixup commits?

### ISSUE THREAD

**Issue by TomasVotruba** [chdsbd/kodiak#477]
In short: I have fixup commits (made by another bot) and I'd like to make just 1 by `rebase --interfactive` basically. How can I do that?

Minimalistic PR with 2 mini commits: https://github.com/rectorphp/rector/pull/3838 -

I tried to use `rebase` strategy, but it doesn't seem to handle the job. There are still 2 commits, in PR and in the `master`

**Comment by chdsbd** [comment]
In your example Kodiak merged your pull request using the "merge" method. If you want to use "rebase" you need to update the `.kodiak.toml` on `master` first.

This change to the `.kodiak.toml` would only have an effect after the PR is merged: https://github.com/rectorphp/rector/pull/3838/files#diff-a9c8419416181476c83e6a05ea0c5695R8

I think you also want to quote the word rebase like below:

```toml
[merge]
delete_branch_on_merge = true

# this should merge !fixup commits from Rector, lets give it a try
method = "rebase"
```


I think with a rebase merge your two commits would still end up as two commits on `master`, but you wouldn't have this merge commit: https://github.com/rectorphp/rector/commit/ae1b0acbfe21d7be828bef612429ead6743c3e8b

If you wanted all your commits from your PR to be merged into one you should use "squash".
