### ISSUE TITLE
Added New Required Github Action, Kodiak merged before complete

### ISSUE THREAD

**Issue by aliwatters** [chdsbd/kodiak#719]
Hi -- our kodiak installation is not waiting for "All Jobs Complete" (a required action) -- before merging.

It merged as soon as our label was added. (job completed later)

<img width="911" alt="Screen Shot 2021-09-01 at 2 16 30 PM" src="https://user-images.githubusercontent.com/1106863/131746795-593d7676-3160-4472-8ac5-9ebbbda49ea5.png">

<img width="888" alt="Screen Shot 2021-09-01 at 2 13 04 PM" src="https://user-images.githubusercontent.com/1106863/131746055-8d515df3-86a2-47a8-ab79-6f88e917ca9d.png">

When does kodiak look for new required actions?

**Comment by chdsbd** [comment]
Hi @aliwatters

GitHub allows the PR to merge because the "neutral" status check set by "All Jobs Complete" counts as a passing status check for your GitHub Branch Protection rule.

If you update "All Jobs Complete" to set an in-progress status check instead of a neutral check, your branch protection configuration should work correctly and Kodiak will wait for the status check to pass before merging.

Do you have a link to the "All Jobs Complete" action?

**Comment by fabiendem** [comment]
Hi @chdsbd 
Sorry what do you mean by _"in-progress status check instead of a neutral check"_?
We can't find any ref to this in the docs.

"All Jobs complete" looks like:
```
done:
    runs-on: ubuntu-latest
    name: All Jobs Complete
    needs:
      - build
      - lint
      - setup
      - test
    steps:
      - run: echo "Hurrah!"
```

**Comment by chdsbd** [comment]
@fabiendem I just tried on a test repository with "All Jobs Completed" set as a required status check and couldn't reproduce the behavior described in this issue.

In my test case, GitHub blocked merging until "All Jobs Complete" had finished.

```yml
name: Example CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "yes!!"
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "yes!!"
  done:
      runs-on: ubuntu-latest
      name: All Jobs Complete
      needs:
        - build
        - test
      steps:
        - run: echo "Hurrah!"
```

**Comment by fabiendem** [comment]
Thanks.
I think it's because the "All Jobs Complete" is skipped if one test step fails.

<img width="1260" alt="Screenshot 2021-09-02 at 17 50 37" src="https://user-images.githubusercontent.com/1186282/131884892-b837728e-5b7a-41e0-b94b-769797c8860f.png">

We may need to prevent the cancellation of all steps if one fails.

**Comment by aliwatters** [comment]
right -- we need that final step to always run -- or is there a way we can configure kodiak to specifically look for a succes?

**Comment by chdsbd** [comment]
@aliwatters This config using https://github.com/technote-space/workflow-conclusion-action seems to work for me.

```yml
name: Example CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "yes!!"
  test:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  done:
    runs-on: ubuntu-latest
    name: All Jobs Complete
    needs:
      - build
      - test
    if: always()
    steps:
        # run this action to get workflow conclusion
        # You can get conclusion via env (env.WORKFLOW_CONCLUSION)
      - uses: technote-space/workflow-conclusion-action@v2
      - run: exit 1
        if: env.WORKFLOW_CONCLUSION == 'failure'
```

Kodiak depends on GitHub Branch Protection for disallowing merging a PR. If GitHub allows the PR to merge, Kodiak will merge it.
