### ISSUE TITLE
Restrict merges to PRs older than a certain threshold

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [chdsbd/kodiak#839]
Vaguely similar to #323, but not quite the same. Could we require PRs be older than some minimum age before merging them?

A few use cases where this'd be very useful:

* Dependabot/Snyk/etc updates, waiting X days in case the community discovers malware in a new package
* Keeping alive for reviews: keeping a PR open for X hours or days so more than one approving reviewer gets a chance to review
* Staging builds: making sure a staging PR and its environment is kept alive for some X hours or days before merge

I'm very motivated to get this in for the first bullet on auto-updates, so if you think this is something a first-time contributor could tackle, I'd love to send a PR! 💖

**Comment by chdsbd** [comment]
I think this is doable. Maybe not the easiest change for a new contributor because we'd need some cron-like functionality.

I think we'd store a PR for reevaluation after some period (N) and then have a cron job that runs every minute or something and checks for PRs that are old enough to merge.

Here's how we mark a PR for evaluation: https://github.com/chdsbd/kodiak/blob/444145f26106e748f497746a25bfc2314b8d510e/bot/kodiak/queue.py#L558-L560

Do you imagine this would be configurable to only affect PRs opened by specific users? Would repo users still be able to manually merge the PR before the time period is up?

Also, do you have ideas about what the configuration would look like?


```toml
[merge.after_period]
# only enforce for specified usernames.
usernames = ["dependabot[bot]", "snyk-bot"]
# only merge PRs after the specified age for days
days = 14
```
