### ISSUE TITLE
Auto merge certain dependencies by name

### ISSUE THREAD

**Issue by chdsbd** [chdsbd/kodiak#860]
Some dependency updates require manual review before merge, while others should auto merge.

For example, we might allow lodash updates automatically, but require TypeScript updates to be reviewed manually.

We need new configuration options to support this

```toml
[update]
ignored_dependencies = ["typescript"]
```
