### ISSUE TITLE
Kodiak shows skipped status check as failure and doesn't update/merge the PR

### ISSUE THREAD

**Issue by erezrokah** [chdsbd/kodiak#885]
Example PR in https://github.com/cloudquery/cloudquery/pull/17769

`Validate PR title` is shown as skipped but Kodiak thinks it failed:
![image](https://github.com/chdsbd/kodiak/assets/26760571/641d8afd-707e-4525-90a4-2cad55be9a2c)
![image](https://github.com/chdsbd/kodiak/assets/26760571/12da3877-77cf-4731-9153-5db1bdb31be5)

This is the workflow https://github.com/cloudquery/cloudquery/blob/222aa899288cdea653d485a155b82aabd0c8f4e0/.github/workflows/validate_pr_title.yml#L15

Please notice we have a condition on the job so a skipped job should be counted as success.
Kodiak config https://github.com/cloudquery/cloudquery/blob/222aa899288cdea653d485a155b82aabd0c8f4e0/.github/.kodiak.toml
```toml

version = 1

[approve]
auto_approve_usernames = ["cq-bot"]

[merge.message]
body = "pull_request_body"
strip_html_comments = true
title = "pull_request_title"

[merge.automerge_dependencies]
usernames = ["cq-bot"]
versions = ["patch"]

[merge]
blocking_labels = ["wip", "no automerge"]
notify_on_conflict = false
priority_merge_label = "priority merge"
```
